package com.ykesoft.service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * GSMService service = new GSMService();
 * GSMServiceDelegate portType = service.getGSMServicePort();
 * portType.sendMsg(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "GSMService", targetNamespace = "http://service.ykesoft.com/", wsdlLocation = "http://192.168.1.253:8880/GSM/GSMServicePort?wsdl")
public class GSMService extends Service {

	private final static URL GSMSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.ykesoft.service.GSMService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.ykesoft.service.GSMService.class.getResource(".");
			url = new URL(baseUrl,
					"http://192.168.1.253:8880/GSM/GSMServicePort?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://192.168.1.253:8880/GSM/GSMServicePort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		GSMSERVICE_WSDL_LOCATION = url;
	}

	public GSMService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public GSMService() {
		super(GSMSERVICE_WSDL_LOCATION, new QName(
				"http://service.ykesoft.com/", "GSMService"));
	}

	/**
	 * 
	 * @return returns GSMServiceDelegate
	 */
	@WebEndpoint(name = "GSMServicePort")
	public GSMServiceDelegate getGSMServicePort() {
		return super.getPort(new QName("http://service.ykesoft.com/",
				"GSMServicePort"), GSMServiceDelegate.class);
	}

}
